[package]
name = "drawing"
version = "0.1.0"
authors = ["K11E3R prs.online.00@gmail.com"]
edition = "2021"

[dependencies]
raster = "0.2.0"
rand = "0.8.5"

[[test]]
<<<<<<< HEAD

name = "shape_color_test"
=======
name = "test_geometrical_shapes"
>>>>>>> 5d3c4bf279ee25186971c6908200034486831bd3
path = "src/test.rs"
